name: Teste de Qualidade do Código

on:
  push:
    branches: [ "main" ]

jobs:
  validar-codigo:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código
      uses: actions/checkout@v3

    - name: Configurar o ambiente Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar o verificador (Flake8)
      run: pip install flake8

    - name: Rodar a inspeção no arquivo app.py
      run: flake8 app.pyname: Teste de Qualidade do Código
